---
title: NexaTech Consulting Ltd.
baseurl: "/Minimal-Text"
desc: NexaTech Ltd Blog
about: NexaTech is a consultancy firm specializing in providing innovative solutions and services to the aerospace and defense industries.
image: https://pinto-light.glitch.me/?width=500&height=500&url=https://josh-mountain.github.io/Minimal-Text/images/test.jpg&extension=jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
